allowBuilds:
  '@fails-components/webtransport-transport-http3-quiche': set this to true or false
  browser-tabs-lock: set this to true or false
  bufferutil: set this to true or false
  core-js: set this to true or false
  node-pty: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-javascript: set this to true or false
  tree-sitter-typescript: set this to true or false
  unrs-resolver: set this to true or false
  utf-8-validate: set this to true or false
overrides:
  lightningcss: 1.30.1
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.20'
  - '@expo/env@2.4.3'
  - '@expo/fingerprint@0.20.11'
  - '@expo/metro-config@57.0.12'
  - expo-constants@57.0.16
  - expo-font@57.0.2
  - expo@57.0.18
