allowBuilds:
  '@fails-components/webtransport-transport-http3-quiche': false
  browser-tabs-lock: false
  bufferutil: true
  core-js: false
  node-pty: false
  tree-sitter: false
  tree-sitter-javascript: false
  tree-sitter-typescript: false
  unrs-resolver: true
  utf-8-validate: true
overrides:
  lightningcss: 1.30.1
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.20'
  - '@expo/env@2.4.3'
  - '@expo/fingerprint@0.20.11'
  - '@expo/metro-config@57.0.12'
  - expo-constants@57.0.16
  - expo-font@57.0.2
  - expo@57.0.18
